version: 2
jobs:
  build:
    docker:
      - image: circleci/<language>:<version TAG>
    steps:
      - checkout
      - run: echo "A first hello"
  test:
    docker:
      - image: circleci/<language>:<version TAG>
    steps:
      - checkout
      - run: echo "A first hello 2"
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
